apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: airquality
    user: airquality_user
    secureJsonData:
      password: airquality_pass
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 30
      connMaxLifetime: 14400
    isDefault: true

 